# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_53447330-aec4-42ab-9d02-639e22e83750
# Generated: 2025-11-24T01:56:13.956Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-11-24-10h
# - Full Path: /2025-11-24-10h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# U-60 SSH Security Configuration Check Script
# Description: Check SSH remote access security settings
# Target: /etc/ssh/sshd_config

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Initialize variables
SSHD_CONFIG="/etc/ssh/sshd_config"
TOTAL_CHECKS=0
FAILED_CHECKS=0

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

# Check if sshd_config exists
if [ ! -f "$SSHD_CONFIG" ]; then
    echo -e "${RED}Error: $SSHD_CONFIG not found${NC}"
    exit 1
fi

echo "=== U-60 SSH Security Configuration Check ==="
echo "Check Time: $(date)"
echo "Target File: $SSHD_CONFIG"
echo

# Function to check configuration
check_config() {
    local param=$1
    local expected=$2
    local actual=$(grep "^${param}" $SSHD_CONFIG | awk '{print $2}')
    
    TOTAL_CHECKS=$((TOTAL_CHECKS+1))
    
    if [ "$actual" = "$expected" ]; then
        echo -e "${GREEN}[PASS]${NC} $param = $actual"
        return 0
    else
        echo -e "${RED}[FAIL]${NC} $param = $actual (Expected: $expected)"
        FAILED_CHECKS=$((FAILED_CHECKS+1))
        return 1
    fi
}

# Function to check if parameter exists
check_param_exists() {
    local param=$1
    if grep -q "^${param}" $SSHD_CONFIG; then
        return 0
    else
        echo -e "${RED}[FAIL]${NC} $param not found in config"
        FAILED_CHECKS=$((FAILED_CHECKS+1))
        return 1
    fi
}

echo "1. Protocol Version Check"
check_config "Protocol" "2"

echo -e "\n2. Root Login Check"
check_config "PermitRootLogin" "no"

echo -e "\n3. Port Configuration Check"
PORT=$(grep "^Port" $SSHD_CONFIG | awk '{print $2}')
TOTAL_CHECKS=$((TOTAL_CHECKS+1))
if [ -z "$PORT" ]; then
    echo -e "${YELLOW}[WARNING]${NC} Port not explicitly set (default: 22)"
elif [ "$PORT" -eq 22 ]; then
    echo -e "${RED}[FAIL]${NC} Default port (22) in use"
    FAILED_CHECKS=$((FAILED_CHECKS+1))
elif [ "$PORT" -gt 1023 ] && [ "$PORT" -lt 65536 ]; then
    echo -e "${GREEN}[PASS]${NC} Custom port configured: $PORT"
else
    echo -e "${RED}[FAIL]${NC} Invalid port number: $PORT"
    FAILED_CHECKS=$((FAILED_CHECKS+1))
fi

echo -e "\n4. Access Restriction Settings"
check_param_exists "MaxAuthTries"
check_config "MaxAuthTries" "3"
check_param_exists "LoginGraceTime"
check_config "LoginGraceTime" "60"

echo -e "\n5. Authentication Settings"
check_config "PasswordAuthentication" "no"
check_config "PubkeyAuthentication" "yes"
check_param_exists "AuthorizedKeysFile"

echo -e "\n6. File Permission Check"
TOTAL_CHECKS=$((TOTAL_CHECKS+1))
PERM=$(stat -c %a "$SSHD_CONFIG")
if [ "$PERM" = "600" ]; then
    echo -e "${GREEN}[PASS]${NC} $SSHD_CONFIG permission is $PERM"
else
    echo -e "${RED}[FAIL]${NC} $SSHD_CONFIG permission is $PERM (should be 600)"
    FAILED_CHECKS=$((FAILED_CHECKS+1))
fi

echo -e "\n=== Check Summary ==="
echo "Total Checks: $TOTAL_CHECKS"
echo "Failed Checks: $FAILED_CHECKS"

if [ $FAILED_CHECKS -eq 0 ]; then
    echo -e "\nOverall Status: ${GREEN}PASS${NC}"
else
    echo -e "\nOverall Status: ${RED}FAIL${NC}"
    echo -e "\nRecommendations:"
    echo "1. Ensure Protocol 2 is set"
    echo "2. Disable root login"
    echo "3. Change default SSH port"
    echo "4. Set proper access restrictions"
    echo "5. Enable key-based authentication"
    echo "6. Set proper file permissions (600)"
fi

exit $FAILED_CHECKS
```