# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_d2f88c32-a89c-4cf4-9de2-7fde1925ae6c
# Generated: 2025-11-21T09:29:21.454Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: 보안 점검 대상
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--보안-점검-대상--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-11-21-18h
# - Full Path: /2025-11-21-18h/OS--보안-점검-대상--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# U-61 Unnecessary Service Check Script
# Description: Check and report status of unnecessary services
# Date: $(date)

# Check root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Initialize variables
SCRIPT_ID="U-61"
CHECK_RESULT="PASS"
VULNERABLE_SERVICES=()

# Service list to check
SERVICES=(
    "telnet"
    "ftp" 
    "rsh"
    "rlogin"
    "rexec"
    "finger"
    "tftp"
    "talk"
    "ntalk"
)

echo "=== $SCRIPT_ID Check Result ==="
echo "Check Time: $(date)"
echo "Description: Check unnecessary services"
echo

# Check each service status
echo "1. Checking Service Status"
for service in "${SERVICES[@]}"; do
    # Check if service exists
    if systemctl list-unit-files | grep -q "$service"; then
        status=$(systemctl is-enabled "$service" 2>/dev/null)
        active=$(systemctl is-active "$service" 2>/dev/null)
        
        echo "Service: $service"
        echo "Status: $status / $active"
        
        if [[ "$status" != "disabled" || "$active" == "active" ]]; then
            CHECK_RESULT="FAIL"
            VULNERABLE_SERVICES+=("$service")
        fi
    else
        echo "Service: $service (not installed)"
    fi
    echo
done

# Check FTP specific configurations if installed
echo "2. Checking FTP Configuration"
if [ -f /etc/vsftpd.conf ]; then
    echo "VSFTPD configuration found"
    
    # Check anonymous access
    if grep -q "^anonymous_enable=YES" /etc/vsftpd.conf; then
        CHECK_RESULT="FAIL"
        echo "[FAIL] Anonymous FTP access is enabled"
    else
        echo "[PASS] Anonymous FTP access is disabled"
    fi
    
    # Check ftpusers file
    for ftpuser_file in "/etc/ftpusers" "/etc/vsftpd/ftpusers"; do
        if [ -f "$ftpuser_file" ]; then
            perms=$(stat -c "%a" "$ftpuser_file")
            if [[ ! "$perms" =~ ^(600|640|644|755)$ ]]; then
                CHECK_RESULT="FAIL"
                echo "[FAIL] $ftpuser_file has incorrect permissions: $perms"
            else
                echo "[PASS] $ftpuser_file permissions are correct: $perms"
            fi
        fi
    done
fi

echo
echo "=== Check Result Summary ==="
echo "Overall Status: $CHECK_RESULT"

if [ "$CHECK_RESULT" == "FAIL" ]; then
    echo "Found Issues:"
    if [ ${#VULNERABLE_SERVICES[@]} -gt 0 ]; then
        echo "- Active/Enabled unnecessary services: ${VULNERABLE_SERVICES[*]}"
    fi
    echo
    echo "Recommendations:"
    echo "1. Disable unnecessary services using: systemctl disable <service>"
    echo "2. Stop running services using: systemctl stop <service>"
    if [ -f /etc/vsftpd.conf ]; then
        echo "3. Set 'anonymous_enable=NO' in /etc/vsftpd.conf"
        echo "4. Ensure correct permissions on FTP configuration files"
    fi
else
    echo "No security issues found"
fi

exit 0
```