# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f7b2c9a4-70be-454f-b0e9-a062db03ec2e
# Generated: 2025-12-15T06:52:26.921Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: System-auth
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--System-auth--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-15-15h
# - Full Path: /2025-12-15-15h/OS--System-auth--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/pam.d/system-auth
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# === U-301 점검 결과 ===
# 스크립트 정보: U-301
# 생성 시간: $(date)
# 설정 적용: configPath=/etc/pam.d/system-auth

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting." >&2; exit 1' ERR

# 점검 결과 변수 초기화
final_exit_code=0
check_count=0
fail_count=0

# SSH 설정 파일 경로
config_file="/etc/ssh/sshd_config"

# 결과 출력 함수
function report_result {
    local item="$1"
    local status="$2"
    local message="$3"
    echo "$item"
    echo "   [$status] $message"
    check_count=$((check_count + 1))
    if [[ "$status" == "FAIL" ]]; then
        fail_count=$((fail_count + 1))
        final_exit_code=1
    fi
}

# 점검 로직 시작
echo "=== 점검 항목 ==="

# 1. SSH 설정 파일 존재 여부 확인
if [[ ! -f "$config_file" ]]; then
    report_result "1. SSH 설정 파일 존재 여부" "FAIL" "File $config_file does not exist."
    final_exit_code=1
else
    # 2. SSH 설정 파일 파싱 (주석 및 공백 제거)
    ssh_config=$(grep -vE '^\s*#|^\s*$' "$config_file")

    # 3. PermitRootLogin 지시자 확인
    if echo "$ssh_config" | grep -q '^PermitRootLogin yes'; then
        report_result "2. PermitRootLogin 설정" "FAIL" "PermitRootLogin is set to 'yes'."
    elif ! echo "$ssh_config" | grep -q '^PermitRootLogin'; then
        report_result "2. PermitRootLogin 설정" "FAIL" "PermitRootLogin is not set (default is 'yes')."
    elif echo "$ssh_config" | grep -q '^PermitRootLogin no'; then
        report_result "2. PermitRootLogin 설정" "PASS" "PermitRootLogin is correctly set to 'no'."
    fi

    # 4. Match 블록 확인
    if echo "$ssh_config" | grep -q 'Match'; then
        report_result "3. Match 블록 존재 여부" "WARNING" "Match block found, check for exceptions."
    fi
fi

# 결과 요약 출력
echo "=== 점검 결과 요약 ==="
echo "전체 평가: $(if [[ $fail_count -eq 0 ]]; then echo 'Good'; else echo 'Vulnerable'; fi)"
echo "발견된 문제: $fail_count"
echo "권장 조치사항: Ensure PermitRootLogin is set to 'no' and check for any Match blocks."

# 최종 결과 출력
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code
```