# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f21c8e1d-ee2a-41d2-85bb-9a23b06992ab
# Generated: 2025-12-16T06:40:56.874Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: System-auth
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--System-auth--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-15h
# - Full Path: /2025-12-16-15h/OS--System-auth--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/pam.d/system-auth
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-301 Security Check Script
# Created on: $(date)
# Configuration Path: /etc/pam.d/system-auth

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

configPath="/etc/ssh/sshd_config"
final_exit_code=0

# Function to check PermitRootLogin setting
check_permit_root_login() {
    local permit_root_login
    permit_root_login=$(grep -E '^\s*PermitRootLogin\s+' "$configPath" | sed 's/#.*//;s/^\s*//;s/\s*$//')

    if [[ -z "$permit_root_login" ]]; then
        permit_root_login="yes"  # Default value for older versions
    fi

    if [[ "$permit_root_login" == "no" ]]; then
        echo "PermitRootLogin is set to 'no'. [PASS]"
        return 0
    else
        echo "PermitRootLogin is set to '$permit_root_login'. [FAIL]"
        return 1
    fi
}

# Function to check for Match blocks
check_match_blocks() {
    local match_blocks
    match_blocks=$(grep -E '^\s*Match\s+' "$configPath")

    if [[ -n "$match_blocks" ]]; then
        echo "Warning: Match blocks found in configuration. Please review."
        echo "$match_blocks"
    fi
}

# Main check execution
echo "+++   U-301   +++"
if [[ ! -f "$configPath" ]]; then
    echo "Configuration file $configPath does not exist. [FAIL]"
    final_exit_code=1
else
    check_permit_root_login || final_exit_code=1
    check_match_blocks
fi
echo "---   U-301   ---"

# Final result summary
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code