# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_26f05e46-eb49-4fb3-a41d-60dc4a784ee1
# Generated: 2025-12-15T07:04:22.200Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-15-16h
# - Full Path: /2025-12-15-16h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-401 점검 스크립트
# 생성 시간: $(date)
# 설정 적용: [targetOS: Linux, outputFormat: bash]

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting." >&2; exit 1' ERR

# 점검할 SUID/SGID 파일 목록 정의
declare -a files=(
    "/sbin/dump"
    "/usr/bin/lpq-lpd"
)

# 최종 결과 변수 초기화
final_exit_code=0
issue_count=0

# 점검 함수 정의
check_suid_sgid() {
    local file_path="$1"
    
    if [[ -e "$file_path" ]]; then
        # 파일의 퍼미션 비트 확인
        local permissions
        permissions=$(stat -c "%a" "$file_path")
        
        if (( (permissions & 4000) != 0 )); then
            echo "Warning: SUID bit found on $file_path"
            return 1
        elif (( (permissions & 2000) != 0 )); then
            echo "Warning: SGID bit found on $file_path"
            return 1
        else
            return 0
        fi
    else
        # 파일이 존재하지 않으면 Pass
        return 0
    fi
}

# 점검 시작
echo "=== U-401 점검 결과 ==="
echo "점검 시간: $(date)"
echo "설정 적용: [targetOS: Linux, outputFormat: bash]"

for file in "${files[@]}"; do
    echo "+++   Checking $file   +++"
    if check_suid_sgid "$file"; then
        echo "1. $file"
        echo "   [PASS] No SUID/SGID bits found."
    else
        echo "1. $file"
        echo "   [FAIL] SUID/SGID bits found."
        final_exit_code=1
        issue_count=$((issue_count + 1))
    fi
    echo "---   Checking $file   ---"
done

# 최종 결과 출력
echo "=== 점검 결과 요약 ==="
if [[ $final_exit_code -eq 0 ]]; then
    echo "전체 평가: Good"
else
    echo "전체 평가: Vulnerable"
fi
echo "발견된 문제: $issue_count 개"
echo "권장 조치사항: SUID/SGID 비트를 제거하거나 해당 파일을 검토하세요."

# 최종 결과 출력
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code