# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_86685410-1624-4ddd-ad5f-e0b85c9a1c5c
# Generated: 2025-12-15T07:26:19.168Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-15-16h
# - Full Path: /2025-12-15-16h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-501
# Created on: $(date)
# Summary of settings: Log configuration check for syslog.conf or rsyslog.conf

echo "Checking log configuration files..."

# Initialize variables
CONFIG_FILE=""
RESULT="Pass"
ISSUES=0

# Check for the existence of syslog.conf or rsyslog.conf
if [ -f /etc/syslog.conf ]; then
    CONFIG_FILE="/etc/syslog.conf"
elif [ -f /etc/rsyslog.conf ]; then
    CONFIG_FILE="/etc/rsyslog.conf"
else
    echo "No configuration file found for syslog."
    RESULT="Fail"
    ISSUES=$((ISSUES + 1))
fi

# Function to check for required patterns
check_pattern() {
    local pattern="$1"
    local description="$2"
    if ! grep -qE "$pattern" "$CONFIG_FILE"; then
        echo "$description: Fail"
        RESULT="Fail"
        ISSUES=$((ISSUES + 1))
    else
        echo "$description: Pass"
    fi
}

# If configuration file exists, check for required settings
if [ -n "$CONFIG_FILE" ]; then
    # Check for required log settings
    check_pattern '.*\.alert.*\/dev\/console' "Check for *.alert -> /dev/console"
    check_pattern '.*\.emerg.*\*' "Check for *.emerg -> *"
    check_pattern 'mail\.debug.*\/var\/log\/maillog' "Check for mail.debug -> /var/log/maillog"
    check_pattern '.*\.info;mail\.none;authpriv\.none;cron\.none.*\/var\/log\/messages' "Check for *.info;mail.none;authpriv.none;cron.none -> /var/log/messages"
fi

# Final result output
echo "=== U-501 Check Result ==="
echo "Check Time: $(date)"
echo "Settings Applied: [Log configuration check for syslog.conf or rsyslog.conf]"

# Output the result of checks
if [ "$RESULT" == "Pass" ]; then
    echo "Overall Assessment: Good"
else
    echo "Overall Assessment: Vulnerable"
fi

echo "Issues Found: $ISSUES"
echo "Final Result: $RESULT"