# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_2141be39-35c0-4b6d-8698-8af23a88f307
# Generated: 2025-12-09T09:01:56.491Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-09-18h
# - Full Path: /2025-12-09-18h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# U-501 Log Configuration Check Script
# Checks syslog/rsyslog configuration settings
# Version: 1.0

# Initialize variables
SCRIPT_NAME="U-501"
CHECK_RESULT="Pass"
LOG_FILES=("/etc/syslog.conf" "/etc/rsyslog.conf")
FOUND_CONFIG=0

# Function to check if pattern exists (allowing for variations)
check_pattern() {
    local file=$1
    local pattern=$2
    local desc=$3
    
    if grep -v "^#" "$file" | grep -q "$pattern"; then
        echo "[PASS] Found $desc configuration"
        return 0
    else
        echo "[FAIL] Missing $desc configuration"
        CHECK_RESULT="Fail"
        return 1
    fi
}

echo "=== $SCRIPT_NAME Log Configuration Check ==="
echo "Check Time: $(date)"
echo

# Check if log config files exist and are readable
for config_file in "${LOG_FILES[@]}"; do
    if [[ -f "$config_file" && -r "$config_file" ]]; then
        FOUND_CONFIG=1
        echo "Checking configuration file: $config_file"
        echo

        # Check required patterns
        check_pattern "$config_file" ".*alert.*\/dev\/console" "system alerts to console"
        check_pattern "$config_file" ".*emerg.*\*" "emergency messages to all users"
        check_pattern "$config_file" "mail.*debug.*\/var\/log\/maillog" "mail logging"
        check_pattern "$config_file" ".*info;mail.none;authpriv.none;cron.none.*\/var\/log\/messages" "general system logging"
        
        echo
        break
    fi
done

if [ $FOUND_CONFIG -eq 0 ]; then
    echo "[ERROR] No readable syslog configuration file found"
    CHECK_RESULT="Fail"
fi

echo "=== Check Summary ==="
if [ "$CHECK_RESULT" = "Pass" ]; then
    echo "Status: All required log configurations are properly set"
else
    echo "Status: One or more required log configurations are missing"
fi
echo
echo "Final Result: $CHECK_RESULT"

exit 0
```