# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f7b2c9a4-70be-454f-b0e9-a062db03ec2e
# Generated: 2025-12-15T08:17:51.414Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-15-17h
# - Full Path: /2025-12-15-17h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-301
# Creation Date: $(date)
# Configuration Summary: Checking SSH root login restrictions in /etc/ssh/sshd_config

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

configPath="/etc/ssh/sshd_config"
final_exit_code=0

# Function to check PermitRootLogin setting
check_permit_root_login() {
    local permit_root_login
    # Load the configuration file into an array, ignoring comments and empty lines
    mapfile -t lines < <(grep -E -v '^\s*#|^\s*$' "$configPath")

    for line in "${lines[@]}"; do
        # Check for PermitRootLogin directive
        if [[ "$line" =~ ^PermitRootLogin ]]; then
            permit_root_login=$(echo "$line" | awk '{print $2}')
            if [[ "$permit_root_login" == "no" ]]; then
                echo "PermitRootLogin is set to 'no'. [PASS]"
                return 0
            else
                echo "PermitRootLogin is set to '$permit_root_login'. [FAIL]"
                return 1
            fi
        fi
    done

    # If PermitRootLogin is not found, it defaults to 'yes'
    echo "PermitRootLogin directive is missing or set to default 'yes'. [FAIL]"
    return 1
}

# Start of the check
echo "+++   U-301   +++"
echo "Checking SSH root login restrictions..."

# Check the configuration file existence
if [[ ! -f "$configPath" ]]; then
    echo "Configuration file $configPath does not exist. [FAIL]"
    final_exit_code=1
else
    # Perform the check
    check_permit_root_login || final_exit_code=1
fi

echo "---   U-301   ---"

# Final result summary
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code