# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_86685410-1624-4ddd-ad5f-e0b85c9a1c5c
# Generated: 2025-12-15T08:22:14.115Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-15-17h
# - Full Path: /2025-12-15-17h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-501 Log Configuration Check Script
# Created on: $(date)
# Target OS: Linux

echo "Checking log configuration files..."

# Initialize result variables
result="Pass"
issues=0

# Check for syslog configuration files
if [ ! -r /etc/syslog.conf ] && [ ! -r /etc/rsyslog.conf ]; then
    echo "Error: Neither /etc/syslog.conf nor /etc/rsyslog.conf exists or is readable."
    result="Fail"
    issues=$((issues + 1))
else
    # Define required patterns
    required_patterns=(
        "*.alert    /dev/console"
        "*.emerg    *"
        "mail.debug  /var/log/maillog"
        "*.info;mail.none;authpriv.none;cron.none  /var/log/messages"
    )

    # Check each configuration file
    for config_file in /etc/syslog.conf /etc/rsyslog.conf; do
        if [ -r "$config_file" ]; then
            echo "Checking $config_file..."
            for pattern in "${required_patterns[@]}"; do
                if ! grep -q -E -v '^#' "$config_file" | grep -q "$pattern"; then
                    echo "Missing required pattern: $pattern in $config_file"
                    result="Fail"
                    issues=$((issues + 1))
                fi
            done
        fi
    done
fi

# Final result output
echo "=== U-501 Check Result ==="
echo "Check Time: $(date)"
echo "Settings Applied: [Log configuration checks]"

if [ "$result" == "Pass" ]; then
    echo "Overall Assessment: Good"
else
    echo "Overall Assessment: Vulnerable"
fi

echo "Issues Found: $issues"
echo "Recommended Actions: Ensure all required log patterns are present in the configuration files."

echo "Final Result: $result"