# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_09e6dafd-64e8-4dd9-b1cf-324feddc46de
# Generated: 2025-12-08T05:56:03.859Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-08-14h
# - Full Path: /2025-12-08-14h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

```bash
#!/bin/bash

# MYS-101: MySQL/MariaDB Root Account Access Check
# Version: 1.0

set -euo pipefail

# Initialize variables
CI_NUMBER="MYS-101"
MYSQL_CONF="/etc/my.cnf"
INI_FILE="qualys_conf.ini"
TIMEOUT_DURATION=10
FINAL_RESULT=0

# Function to log messages
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Function to check if command exists
check_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        log_message "ERROR: Required command '$1' not found"
        exit 1
    fi
}

# Print header
echo "+++ $CI_NUMBER +++"

# Check required commands
check_command mysql
check_command grep
check_command awk

# Check if config file exists
if [ ! -f "$INI_FILE" ]; then
    log_message "ERROR: Configuration file $INI_FILE not found"
    echo "Result: Fail (Missing configuration file)"
    echo "--- $CI_NUMBER ---"
    exit 1
fi

# Get DB credentials from ini file
DB_USER=$(awk -F '=' '/^\[mysql\]/{f=1;next} /^\[/{f=0} f&&$1=="user"{print $2}' "$INI_FILE" | tr -d ' ')
DB_PASS=$(awk -F '=' '/^\[mysql\]/{f=1;next} /^\[/{f=0} f&&$1=="password"{print $2}' "$INI_FILE" | tr -d ' ')

# Check if credentials were found
if [ -z "$DB_USER" ] || [ -z "$DB_PASS" ]; then
    log_message "ERROR: Database credentials not found in config file"
    echo "Result: Fail (Missing credentials)"
    echo "--- $CI_NUMBER ---"
    exit 1
fi

# Check MySQL/MariaDB process
if ! pgrep -f "mysqld|mariadbd" >/dev/null; then
    log_message "ERROR: MySQL/MariaDB process not running"
    echo "Result: Fail (Database not running)"
    echo "--- $CI_NUMBER ---"
    exit 1
fi

# Function to check root access
check_root_access() {
    local query="SELECT user, host FROM mysql.user WHERE user='root';"
    local result
    
    result=$(timeout "$TIMEOUT_DURATION" mysql -u"$DB_USER" -p"$DB_PASS" -N -B -e "$query" 2>/dev/null)
    
    if [ $? -ne 0 ]; then
        log_message "ERROR: Failed to execute MySQL query"
        echo "Result: Fail (Query execution failed)"
        return 1
    }
    
    if [ -n "$result" ]; then
        while IFS=$'\t' read -r user host; do
            if [ "$host" = "%" ]; then
                log_message "WARNING: Root account allows remote access from any host"
                echo "Result: Fail (Root allows remote access)"
                return 1
            fi
            if [ "$host" != "localhost" ] && [ "$host" != "127.0.0.1" ]; then
                log_message "WARNING: Root account allows access from non-localhost: $host"
                echo "Result: Fail (Root allows non-localhost access)"
                return 1
            fi
        done <<< "$result"
    fi
    
    echo "Result: Pass (Root access properly restricted)"
    return 0
}

# Perform the check
if check_root_access; then
    FINAL_RESULT=0
else
    FINAL_RESULT=1
fi

# Print final result
if [ $FINAL_RESULT -eq 0 ]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

echo "--- $CI_NUMBER ---"
exit $FINAL_RESULT
```