# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_9562824a-3722-4454-bb73-45499988722f
# Generated: 2025-12-16T01:23:10.384Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Security
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Security--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-10h
# - Full Path: /2025-12-16-10h/OS--Security--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/security/pwquality.conf
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-102 Security Check Script
# Created on: $(date)
# Configuration Path: /etc/security/pwquality.conf

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

configPath="/etc/security/pwquality.conf"
final_exit_code=0

# Function to check password quality settings
check_password_quality() {
    local minlen
    local dcredit
    local ucredit
    local lcredit
    local ocredit
    local retry
    local issues=0

    # Load the configuration file into an array
    mapfile -t lines < <(grep -vE '^\s*#|^\s*$' "$configPath")

    # Parse the configuration settings
    for line in "${lines[@]}"; do
        case "$line" in
            minlen=*)
                minlen="${line#*=}"
                ;;
            dcredit=*)
                dcredit="${line#*=}"
                ;;
            ucredit=*)
                ucredit="${line#*=}"
                ;;
            lcredit=*)
                lcredit="${line#*=}"
                ;;
            ocredit=*)
                ocredit="${line#*=}"
                ;;
            retry=*)
                retry="${line#*=}"
                ;;
        esac
    done

    # Check minlen
    if [[ "${minlen:-0}" -ge 8 ]]; then
        echo "1. Minimum length check: [PASS] Minimum length is ${minlen}."
    else
        echo "1. Minimum length check: [FAIL] Minimum length is ${minlen}. It should be at least 8."
        issues=$((issues + 1))
    fi

    # Check dcredit, ucredit, lcredit, ocredit
    if [[ "${dcredit:-0}" -le -1 || "${ucredit:-0}" -le -1 || "${lcredit:-0}" -le -1 || "${ocredit:-0}" -le -1 ]]; then
        echo "2. Credit checks: [PASS] At least one credit setting is -1 or less."
    else
        echo "2. Credit checks: [FAIL] All credit settings are above -1."
        issues=$((issues + 1))
    fi

    # Check retry
    if [[ "${retry:-0}" -le 3 ]]; then
        echo "3. Retry check: [PASS] Retry count is ${retry}."
    else
        echo "3. Retry check: [FAIL] Retry count is ${retry}. It should be 3 or less."
        issues=$((issues + 1))
    fi

    # Return the number of issues found
    return $issues
}

# Check if the configuration file exists
if [[ ! -f "$configPath" ]]; then
    echo "Configuration file $configPath does not exist. [FAIL]"
    final_exit_code=1
else
    check_password_quality
    if [[ $? -ne 0 ]]; then
        final_exit_code=1
    fi
fi

# Summary of the results
echo "=== U-102 Security Check Results ==="
echo "Check Time: $(date)"
echo "Configuration Path: $configPath"

if [[ $final_exit_code -eq 0 ]]; then
    echo "Overall Assessment: Good"
else
    echo "Overall Assessment: Vulnerable"
fi

echo "Final Result: $(if [[ $final_exit_code -eq 0 ]]; then echo 'Pass'; else echo 'Fail'; fi)"
exit $final_exit_code