# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_9b4431a6-d098-446a-9c7f-9166c833c76b
# Generated: 2025-12-16T01:22:52.914Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Security
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Security--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-10h
# - Full Path: /2025-12-16-10h/OS--Security--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/security/pwquality.conf
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-501
# Description: Check log configuration files for security compliance
# Created on: $(date)

echo "Checking log configuration files..."

# Initialize variables
result="Pass"
issues=0
log_file="/etc/syslog.conf"
rsyslog_file="/etc/rsyslog.conf"

# Function to check for required patterns
check_patterns() {
    local file=$1
    local patterns=(
        "*.alert    /dev/console"
        "*.emerg    *"
        "mail.debug  /var/log/maillog"
        "*.info;mail.none;authpriv.none;cron.none  /var/log/messages"
    )
    
    for pattern in "${patterns[@]}"; do
        if ! grep -q -E -v '^#' <<< "$(cat "$file")" | grep -q "$pattern"; then
            echo "Missing required pattern: $pattern in $file"
            ((issues++))
        fi
    done
}

# Check if syslog.conf or rsyslog.conf exists
if [[ -f "$log_file" ]]; then
    check_patterns "$log_file"
elif [[ -f "$rsyslog_file" ]]; then
    check_patterns "$rsyslog_file"
else
    echo "Neither $log_file nor $rsyslog_file exists."
    result="Fail"
    ((issues++))
fi

# Determine final result
if [[ $issues -gt 0 ]]; then
    result="Fail"
fi

# Output results
echo "=== U-501 Check Results ==="
echo "Check Time: $(date)"
echo "Settings Applied: [Log configuration checks]"

if [[ $result == "Pass" ]]; then
    echo "1. Log configuration check"
    echo "   PASS: All required patterns are present."
else
    echo "1. Log configuration check"
    echo "   FAIL: Issues found in log configuration."
fi

echo "=== Summary of Check Results ==="
echo "Overall Assessment: $result"
echo "Issues Found: $issues"
echo "Recommended Actions: Ensure all required log patterns are present in the configuration file."

# Final result output
echo "Final Result: $result"