# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f5e06fe7-5675-48b2-98db-40376e891596
# Generated: 2025-12-16T04:36:21.558Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Security
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Security--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-13h
# - Full Path: /2025-12-16-13h/OS--Security--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/security/pwquality.conf
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-102
# Created on: $(date)
# Configuration Path: /etc/security/pwquality.conf

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

# Initialize variables
configPath="/etc/security/pwquality.conf"
final_exit_code=0
issues_found=0

# Function to check minimum length
check_minlen() {
    local minlen_value
    minlen_value=$(grep -E '^\s*minlen\s*=\s*[0-9]+' "$configPath" | awk -F '=' '{print $2}' | tr -d ' ')
    
    if [[ -z "$minlen_value" ]]; then
        echo "1. Minimum length not set in $configPath"
        issues_found=$((issues_found + 1))
        return 1
    elif (( minlen_value < 8 )); then
        echo "1. Minimum length is less than 8: $minlen_value"
        issues_found=$((issues_found + 1))
        return 1
    else
        echo "1. Minimum length is valid: $minlen_value"
        return 0
    fi
}

# Function to check credit settings
check_credit_settings() {
    local dcredit ucredit lcredit ocredit
    dcredit=$(grep -E '^\s*dcredit\s*=\s*-?[0-9]+' "$configPath" | awk -F '=' '{print $2}' | tr -d ' ')
    ucredit=$(grep -E '^\s*ucredit\s*=\s*-?[0-9]+' "$configPath" | awk -F '=' '{print $2}' | tr -d ' ')
    lcredit=$(grep -E '^\s*lcredit\s*=\s*-?[0-9]+' "$configPath" | awk -F '=' '{print $2}' | tr -d ' ')
    ocredit=$(grep -E '^\s*ocredit\s*=\s*-?[0-9]+' "$configPath" | awk -F '=' '{print $2}' | tr -d ' ')

    if [[ -z "$dcredit" && -z "$ucredit" && -z "$lcredit" && -z "$ocredit" ]]; then
        echo "2. Credit settings not set in $configPath"
        issues_found=$((issues_found + 1))
        return 1
    fi

    if (( dcredit <= -1 || ucredit <= -1 || lcredit <= -1 || ocredit <= -1 )); then
        echo "2. At least one credit setting is valid."
        return 0
    else
        echo "2. All credit settings are above -1."
        issues_found=$((issues_found + 1))
        return 1
    fi
}

# Function to check retry setting
check_retry() {
    local retry_value
    retry_value=$(grep -E '^\s*retry\s*=\s*[0-9]+' "$configPath" | awk -F '=' '{print $2}' | tr -d ' ')

    if [[ -z "$retry_value" ]]; then
        echo "3. Retry setting not set in $configPath"
        issues_found=$((issues_found + 1))
        return 1
    elif (( retry_value > 3 )); then
        echo "3. Retry setting is greater than 3: $retry_value"
        issues_found=$((issues_found + 1))
        return 1
    else
        echo "3. Retry setting is valid: $retry_value"
        return 0
    fi
}

# Start checking
echo "=== U-102 Check Results ==="
echo "Check Time: $(date)"
echo "Configuration Applied: [Path: $configPath]"

check_minlen
check_credit_settings
check_retry

# Final results
if (( issues_found > 0 )); then
    final_exit_code=1
    echo "---   U-102   ---"
    echo "Final Result: Fail"
else
    echo "---   U-102   ---"
    echo "Final Result: Pass"
fi

exit $final_exit_code