# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f5e06fe7-5675-48b2-98db-40376e891596
# Generated: 2025-12-16T04:58:54.822Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Security
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Security--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-13h
# - Full Path: /2025-12-16-13h/OS--Security--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/security/pwquality.conf
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-102 Security Check Script
# Created on: $(date)
# Configuration Path: /etc/security/pwquality.conf

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting." >&2; exit 1' ERR

# Initialize variables
configPath="/etc/security/pwquality.conf"
final_exit_code=0
issues_found=0

# Function to check password complexity settings
check_password_complexity() {
    local minlen
    local dcredit
    local ucredit
    local lcredit
    local ocredit
    local retry
    local result=""

    # Load the configuration file into an associative array
    declare -A config
    while IFS='=' read -r key value; do
        key=$(echo "$key" | sed 's/;.*//;s/[[:space:]]//g') # Remove comments and whitespace
        value=$(echo "$value" | sed 's/[[:space:]]//g') # Remove whitespace
        if [[ -n "$key" && -n "$value" ]]; then
            config["$key"]="$value"
        fi
    done < "$configPath"

    # Check minlen
    minlen=${config["minlen"]:-0}
    if (( minlen >= 8 )); then
        result+="1. Minimum length is sufficient: $minlen (PASS)\n"
    else
        result+="1. Minimum length is insufficient: $minlen (FAIL)\n"
        ((issues_found++))
    fi

    # Check dcredit, ucredit, lcredit, ocredit
    dcredit=${config["dcredit"]:-0}
    ucredit=${config["ucredit"]:-0}
    lcredit=${config["lcredit"]:-0}
    ocredit=${config["ocredit"]:-0}

    if (( dcredit <= -1 || ucredit <= -1 || lcredit <= -1 || ocredit <= -1 )); then
        result+="2. At least one credit setting is sufficient (PASS)\n"
    else
        result+="2. All credit settings are insufficient (FAIL)\n"
        ((issues_found++))
    fi

    # Check retry
    retry=${config["retry"]:-0}
    if (( retry <= 3 )); then
        result+="3. Retry count is acceptable: $retry (PASS)\n"
    else
        result+="3. Retry count is excessive: $retry (FAIL)\n"
        ((issues_found++))
    fi

    echo -e "$result"
}

# Main execution
if [[ ! -f "$configPath" ]]; then
    echo "Configuration file not found: $configPath"
    final_exit_code=1
else
    echo "+++   U-102   +++"
    check_password_complexity
    echo "---   U-102   ---"
fi

# Final result summary
if (( issues_found == 0 )); then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
    final_exit_code=1
fi

exit $final_exit_code