# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_6a48de58-665a-4f07-9eb9-127d8f2e4fe1
# Generated: 2025-12-16T04:02:46.801Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: System-auth
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--System-auth--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-13h
# - Full Path: /2025-12-16-13h/OS--System-auth--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/pam.d/system-auth
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-301
# Created on: $(date)
# Configuration Summary: configPath=/etc/pam.d/system-auth, targetOS=Linux, outputFormat=bash

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

# Function to check PermitRootLogin in sshd_config
check_permit_root_login() {
    local config_file="/etc/ssh/sshd_config"
    
    # Check if the configuration file exists
    if [[ ! -f "$config_file" ]]; then
        echo "+++   U-301   +++"
        echo "Configuration file $config_file does not exist."
        echo "---   U-301   ---"
        return 1
    fi

    # Load the configuration file into an array, ignoring comments and empty lines
    mapfile -t lines < <(grep -vE '^\s*#|^\s*$' "$config_file")

    local permit_root_login_found=0
    local permit_root_login_value=""
    
    # Parse the lines for PermitRootLogin directive
    for line in "${lines[@]}"; do
        if [[ "$line" =~ ^PermitRootLogin ]]; then
            permit_root_login_value=$(echo "$line" | awk '{print $2}')
            permit_root_login_found=1
            break
        fi
    done

    # Check the value of PermitRootLogin
    if [[ $permit_root_login_found -eq 0 ]]; then
        echo "+++   U-301   +++"
        echo "PermitRootLogin directive is not set. Default is 'yes'."
        echo "---   U-301   ---"
        return 1
    elif [[ "$permit_root_login_value" == "yes" ]]; then
        echo "+++   U-301   +++"
        echo "PermitRootLogin is set to 'yes'. This is a security risk."
        echo "---   U-301   ---"
        return 1
    elif [[ "$permit_root_login_value" == "no" ]]; then
        echo "+++   U-301   +++"
        echo "PermitRootLogin is correctly set to 'no'."
        echo "---   U-301   ---"
        return 0
    fi

    # Check for Match blocks that may allow root login
    for line in "${lines[@]}"; do
        if [[ "$line" =~ ^Match ]]; then
            echo "+++   U-301   +++"
            echo "Match block found. Check if it allows root login."
            echo "---   U-301   ---"
            return 1
        fi
    done

    return 0
}

# Main execution
final_exit_code=0

check_permit_root_login || final_exit_code=1

# Final result summary
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code