# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_3bf292c1-972a-4657-9c88-690ae8f5dcce
# Generated: 2025-12-16T05:06:37.508Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-14h
# - Full Path: /2025-12-16-14h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-401 Security Check Script
# Created on: $(date)
# Summary of settings: Target OS: Linux, Output Format: bash

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

# Define the list of files to check for SUID/SGID
files_to_check=(
    "/sbin/dump"
    "/usr/bin/lpq-lpd"
)

# Initialize final exit code
final_exit_code=0

# Function to check SUID/SGID bits
check_suid_sgid() {
    local file="$1"
    if [[ -e "$file" ]]; then
        # Check permissions
        permissions=$(stat -c "%a" "$file")
        if (( (permissions & 4000) != 0 )); then
            echo "Warning: SUID bit found on $file"
            return 1
        elif (( (permissions & 2000) != 0 )); then
            echo "Warning: SGID bit found on $file"
            return 1
        fi
        return 0
    else
        return 0
    fi
}

# Start the security check
echo "=== U-401 Security Check Results ==="
echo "Check Time: $(date)"
echo "Settings Applied: Target OS: Linux, Output Format: bash"

# Loop through the files and check their permissions
for file in "${files_to_check[@]}"; do
    echo "+++   Checking $file   +++"
    if ! check_suid_sgid "$file"; then
        final_exit_code=1
    fi
    echo "---   Checking $file   ---"
done

# Final result summary
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code