# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_fd549ae9-799b-4dd7-970e-b737674738a8
# Generated: 2025-12-16T05:06:41.014Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-14h
# - Full Path: /2025-12-16-14h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# U-501 Log Configuration Check Script
# Created on: $(date)
# Summary of settings: Target OS: Linux, Output Format: bash

echo "Checking log configuration files..."

# Initialize variables
result="Pass"
issues=0

# Check for the existence of syslog configuration files
if [[ ! -f /etc/syslog.conf && ! -f /etc/rsyslog.conf ]]; then
    echo "Error: Neither /etc/syslog.conf nor /etc/rsyslog.conf exists."
    echo "Final Result: Fail"
    exit 1
fi

# Function to check for required log settings
check_log_settings() {
    local file=$1
    local patterns=(
        "*.alert    /dev/console"
        "*.emerg    *"
        "mail.debug  /var/log/maillog"
        "*.info;mail.none;authpriv.none;cron.none  /var/log/messages"
    )
    
    for pattern in "${patterns[@]}"; do
        if ! grep -q -E -v '^#' "$file" | grep -q "$pattern"; then
            echo "Missing required log setting: $pattern in $file"
            ((issues++))
        fi
    done
}

# Check both configuration files if they exist
if [[ -f /etc/syslog.conf ]]; then
    check_log_settings /etc/syslog.conf
fi

if [[ -f /etc/rsyslog.conf ]]; then
    check_log_settings /etc/rsyslog.conf
fi

# Determine final result based on issues found
if [[ $issues -gt 0 ]]; then
    result="Fail"
else
    result="Pass"
fi

# Output the final result
echo "Final Result: $result"