# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_3d7d0c7a-75fe-468b-b1cf-865dfcef0b38
# Generated: 2025-12-16T05:06:47.379Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Linux 서버
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Linux-서버--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-14h
# - Full Path: /2025-12-16-14h/OS--Linux-서버--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/default/config
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-301
# Creation Date: $(date)
# Configuration Summary: 
# configPath: /etc/pam.d/system-auth
# targetOS: Linux
# outputFormat: bash

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

# Function to check PermitRootLogin setting
check_permit_root_login() {
    local config_file="/etc/ssh/sshd_config"
    local permit_root_login
    local match_block_found=0

    # Check if the configuration file exists
    if [[ ! -f "$config_file" ]]; then
        echo "+++   U-301   +++"
        echo "Configuration file not found: $config_file"
        echo "---   U-301   ---"
        return 1
    fi

    # Load the configuration file into an array, ignoring comments and blank lines
    mapfile -t lines < <(grep -vE '^\s*#|^\s*$' "$config_file")

    # Parse the configuration for PermitRootLogin
    for line in "${lines[@]}"; do
        if [[ "$line" =~ ^PermitRootLogin ]]; then
            permit_root_login=$(echo "$line" | awk '{print $2}')
            if [[ "$permit_root_login" == "yes" ]]; then
                echo "+++   U-301   +++"
                echo "PermitRootLogin is set to 'yes'. This is a security risk."
                echo "---   U-301   ---"
                return 1
            elif [[ "$permit_root_login" == "prohibit-password" ]]; then
                echo "+++   U-301   +++"
                echo "PermitRootLogin is set to 'prohibit-password'. This is acceptable."
                echo "---   U-301   ---"
                return 0
            fi
        fi

        # Check for Match blocks that might allow root login
        if [[ "$line" =~ ^Match ]]; then
            match_block_found=1
        fi
    done

    # If no PermitRootLogin directive was found, assume default is 'yes'
    if [[ -z "$permit_root_login" ]]; then
        echo "+++   U-301   +++"
        echo "PermitRootLogin directive is missing. Default is 'yes'. This is a security risk."
        echo "---   U-301   ---"
        return 1
    fi

    # If we found a Match block, warn about it
    if [[ $match_block_found -eq 1 ]]; then
        echo "+++   U-301   +++"
        echo "Match block found. Ensure it does not allow root login."
        echo "---   U-301   ---"
    fi

    return 0
}

# Main execution
final_exit_code=0

check_permit_root_login || final_exit_code=1

# Final result output
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code