# ========================================
# NCU Script Generator - Auto Generated Script
# ========================================
#
# Script ID: detect_f5e06fe7-5675-48b2-98db-40376e891596
# Generated: 2025-12-16T05:02:22.731Z
# Asset Type: OS
# Script Type: OS-Linux
# Target Product: Security
# Generated By: NCU Script Generator User
#
# File Information:
# - File Name: OS--Security--OSLinux-unknown-process.sh
# - Time-based Folder: 2025-12-16-14h
# - Full Path: /2025-12-16-14h/OS--Security--OSLinux-unknown-process.sh
#
# Configuration:
# - Target OS: Linux
# - Process Name: unknown-process
# - Config Path: /etc/security/pwquality.conf
# - Account Name: default-account
# - Output Format: bash
#
# Test Results:
# - Status: FAILED
# - Success Rate: 0%
# - Summary: [object Object]
#
# Pass Condition: Script executed successfully
# Fail Condition: Script execution failed
#
# ========================================

#!/bin/bash

# Script ID: U-102
# Created on: $(date)
# Configuration Path: /etc/security/pwquality.conf
# This script checks the password quality configuration for compliance.

set -Eeuo pipefail
trap 'echo "An error occurred. Exiting."; exit 1;' ERR

configPath="/etc/security/pwquality.conf"
final_exit_code=0

# Function to check the minimum length
check_minlen() {
    local minlen_value
    minlen_value=$(grep -E '^\s*minlen\s*=\s*[0-9]+' "$configPath" | sed 's/.*=\s*//;s/\s*//g')
    
    if [[ -z "$minlen_value" ]]; then
        echo "1. Minimum length (minlen) is not set. [FAIL]"
        final_exit_code=1
        return 1
    elif (( minlen_value < 8 )); then
        echo "1. Minimum length (minlen) is less than 8. [FAIL]"
        final_exit_code=1
        return 1
    else
        echo "1. Minimum length (minlen) is set to $minlen_value. [PASS]"
        return 0
    fi
}

# Function to check credit settings
check_credits() {
    local dcredit_value ucredit_value lcredit_value ocredit_value
    dcredit_value=$(grep -E '^\s*dcredit\s*=\s*-?[0-9]+' "$configPath" | sed 's/.*=\s*//;s/\s*//g')
    ucredit_value=$(grep -E '^\s*ucredit\s*=\s*-?[0-9]+' "$configPath" | sed 's/.*=\s*//;s/\s*//g')
    lcredit_value=$(grep -E '^\s*lcredit\s*=\s*-?[0-9]+' "$configPath" | sed 's/.*=\s*//;s/\s*//g')
    ocredit_value=$(grep -E '^\s*ocredit\s*=\s*-?[0-9]+' "$configPath" | sed 's/.*=\s*//;s/\s*//g')

    if [[ -z "$dcredit_value" && -z "$ucredit_value" && -z "$lcredit_value" && -z "$ocredit_value" ]]; then
        echo "2. Credit settings (dcredit, ucredit, lcredit, ocredit) are not set. [FAIL]"
        final_exit_code=1
        return 1
    fi

    if (( dcredit_value <= -1 || ucredit_value <= -1 || lcredit_value <= -1 || ocredit_value <= -1 )); then
        echo "2. At least one credit setting is set to -1 or less. [PASS]"
        return 0
    else
        echo "2. All credit settings are above -1. [FAIL]"
        final_exit_code=1
        return 1
    fi
}

# Function to check retry setting
check_retry() {
    local retry_value
    retry_value=$(grep -E '^\s*retry\s*=\s*[0-9]+' "$configPath" | sed 's/.*=\s*//;s/\s*//g')

    if [[ -z "$retry_value" ]]; then
        echo "3. Retry setting is not set. [FAIL]"
        final_exit_code=1
        return 1
    elif (( retry_value > 3 )); then
        echo "3. Retry setting is greater than 3. [FAIL]"
        final_exit_code=1
        return 1
    else
        echo "3. Retry setting is set to $retry_value. [PASS]"
        return 0
    fi
}

# Main check execution
echo "+++   U-102   +++"
if [[ ! -f "$configPath" ]]; then
    echo "Configuration file $configPath does not exist. [FAIL]"
    final_exit_code=1
else
    check_minlen
    check_credits
    check_retry
fi
echo "---   U-102   ---"

# Final result output
if [[ $final_exit_code -eq 0 ]]; then
    echo "Final Result: Pass"
else
    echo "Final Result: Fail"
fi

exit $final_exit_code